# This is a basic workflow to help you get started with Actions

name: Build Kernel

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  #push:
  #  branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: "Checkout Code"
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      # Runs a single command using the runners shell
      - name: Set up environment
        run: |
          export PATH="$PATH:${GITHUB_WORKSPACE}/toolchain/bin"  # Replace with actual cross-compiler path
          export CROSS_COMPILE="aarch64-linux-android-"       # Replace with actual cross-compiler prefix
          export ARCH=arm64

      # Runs a set of commands using the runners shell
      - name: Build Kernel
        working-directory: kernel
        run: |
          mkdir ../out
          make ARCH=arm64 O=../out merge_kirin710_defconfig
          make ARCH=arm64 O=../out -j8
          
      - name: Upload Image
        uses: actions/upload-artifact@v3.1.2
        with:
          name: "Image.zip"
          path: ${GITHUB_WORKSPACE}/out/arch/arm64/boot/Image
