# This is a basic workflow to help you get started with Actions

name: Download File

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      link:
        description: File Link
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  download:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Download
        run: wget ${{ github.event.inputs.link }}

      - name: Upload File
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: File
          # A file, directory or wildcard pattern that describes what to upload
          path: ./
